# Generated by Django 2.1.1 on 2018-09-30 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0002_auto_20180930_0116'),
        ('consumer', '0005_auto_20180930_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operative.Operative', verbose_name='operativo'),
        ),
    ]
