# Generated by Django 2.1.1 on 2018-09-30 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_order_base_operative_20180930_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='operative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operative.Operative', verbose_name='operative'),
        ),
    ]
