# Generated by Django 2.1.2 on 2018-11-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0009_auto_20181005_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='pagado'),
        ),
    ]
