# Generated by Django 2.1.1 on 2018-09-30 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_auto_20180913_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name': 'productor', 'verbose_name_plural': 'productores'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'producto'},
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='cantidad mínima'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.Producer', verbose_name='productor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='unidad'),
        ),
    ]
