# Generated by Django 2.1.2 on 2018-11-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_product_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='deshabilitado'),
        ),
    ]
