# Generated by Django 2.1.5 on 2019-02-11 02:11

from django.db import migrations

def forward(apps, schema_editor):
    Category = apps.get_model('producer', 'Category')
    Product = apps.get_model('producer', 'Product')

    # create placeholder category
    category = Category.objects.create(name='Placeholder')

    # set the category on all existing products
    Product.objects.update(category=category)


def backward(apps, schema_editor):
    Product = apps.get_model('producer', 'Product')

    # remove the producer from all existing products
    Product.objects.update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0008_add_category_model'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
