// flow-typed signature: 06f8b8aa7f85d9bd2deb7be368a20a96
// flow-typed version: <<STUB>>/babel-plugin-emotion_v^9.2.8/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-emotion/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-emotion/lib/macro-styled' {
  declare module.exports: any;
}

declare module 'babel-plugin-emotion/lib/macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-emotion/src/babel-utils' {
  declare module.exports: any;
}

declare module 'babel-plugin-emotion/src/css-prop' {
  declare module.exports: any;
}

declare module 'babel-plugin-emotion/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-emotion/src/macro-styled' {
  declare module.exports: any;
}

declare module 'babel-plugin-emotion/src/macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-emotion/src/source-map' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-emotion/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-emotion/dist/index'>;
}
declare module 'babel-plugin-emotion/lib/macro-styled.js' {
  declare module.exports: $Exports<'babel-plugin-emotion/lib/macro-styled'>;
}
declare module 'babel-plugin-emotion/lib/macro.js' {
  declare module.exports: $Exports<'babel-plugin-emotion/lib/macro'>;
}
declare module 'babel-plugin-emotion/src/babel-utils.js' {
  declare module.exports: $Exports<'babel-plugin-emotion/src/babel-utils'>;
}
declare module 'babel-plugin-emotion/src/css-prop.js' {
  declare module.exports: $Exports<'babel-plugin-emotion/src/css-prop'>;
}
declare module 'babel-plugin-emotion/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-emotion/src/index'>;
}
declare module 'babel-plugin-emotion/src/macro-styled.js' {
  declare module.exports: $Exports<'babel-plugin-emotion/src/macro-styled'>;
}
declare module 'babel-plugin-emotion/src/macro.js' {
  declare module.exports: $Exports<'babel-plugin-emotion/src/macro'>;
}
declare module 'babel-plugin-emotion/src/source-map.js' {
  declare module.exports: $Exports<'babel-plugin-emotion/src/source-map'>;
}
