// flow-typed signature: 12e3e90cc1c37c2e49064ab2a892fe68
// flow-typed version: <<STUB>>/wretch_v^1.4.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wretch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wretch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wretch/dist/bundle/wretch' {
  declare module.exports: any;
}

declare module 'wretch/dist/config' {
  declare module.exports: any;
}

declare module 'wretch/dist/index' {
  declare module.exports: any;
}

declare module 'wretch/dist/middleware' {
  declare module.exports: any;
}

declare module 'wretch/dist/mix' {
  declare module.exports: any;
}

declare module 'wretch/dist/perfs' {
  declare module.exports: any;
}

declare module 'wretch/dist/resolver' {
  declare module.exports: any;
}

declare module 'wretch/dist/wretcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wretch/dist/bundle/wretch.js' {
  declare module.exports: $Exports<'wretch/dist/bundle/wretch'>;
}
declare module 'wretch/dist/config.js' {
  declare module.exports: $Exports<'wretch/dist/config'>;
}
declare module 'wretch/dist/index.js' {
  declare module.exports: $Exports<'wretch/dist/index'>;
}
declare module 'wretch/dist/middleware.js' {
  declare module.exports: $Exports<'wretch/dist/middleware'>;
}
declare module 'wretch/dist/mix.js' {
  declare module.exports: $Exports<'wretch/dist/mix'>;
}
declare module 'wretch/dist/perfs.js' {
  declare module.exports: $Exports<'wretch/dist/perfs'>;
}
declare module 'wretch/dist/resolver.js' {
  declare module.exports: $Exports<'wretch/dist/resolver'>;
}
declare module 'wretch/dist/wretcher.js' {
  declare module.exports: $Exports<'wretch/dist/wretcher'>;
}
