# Generated by Django 2.1.1 on 2018-10-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0002_auto_20180930_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operative',
            options={'get_latest_by': ('-start_date',), 'verbose_name': 'operativo'},
        ),
    ]
