# Generated by Django 2.1.2 on 2018-10-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0003_auto_20181005_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operative',
            options={'get_latest_by': ('start_date',), 'verbose_name': 'operativo'},
        ),
    ]
