# Build
FROM node:10.9.0-alpine AS build

WORKDIR /opt/app
COPY . ./
RUN yarn install
RUN yarn build

# Release
FROM nginx:1.15.3-alpine
LABEL maintainer="asermax@gmail.com"

COPY --from=build /opt/app/dist /usr/share/nginx/html
COPY nginx-prod.conf /etc/nginx/conf.d/default.conf
